[package]
name = "advent_of_rust_2020"
version = "0.1.0"
authors = ["Logan Smith <loganda.smith@ufl.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
